#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=21:00:00
#PBS -l mem=512GB
#PBS -N randomisation_hpc
#PBS -M ld1439@nyu.edu
#PBS -j oe

module load matlab/2014a

cd /scratch/ld1439/data

# If the files you are running are not in the same folder as this script,
# you can insert "addpath(genpath('/PATH/TO/FILES/'));" before the command
# you want to run.
matlab -nodisplay -r "addpath(genpath('/scratch/ld1439/endo_exo_MRI/‘)); randomisation_hpc(‘endo’); exit()"

exit
  
  
  
  
